### ISSUE TITLE
Problem with npm run build:prod

### ISSUE THREAD

**Issue by AndreasCag** [dvhbru/webpack#21]
Hello!
Thanks for this package, it incredibly improve layout development speed.

Recently I met small bug:
when I run `npm run build:prod`, build folder doesn't have any html.
I found that my project folder named `html` and [this](https://github.com/dvhb/webpack/blob/master/gulp/tasks/templates.js#L27) code ignore all my .pug files.

Though it is not a big problem, I spent some time to find it out :)

**Comment by alexbee** [comment]
@AndreasCag, thanks for the feedback! In fact, this is not a bug, but a feature. 
In `src/views/html/*` we develop a static layout for development purpose only.

On development server execute command `yarn build:dev` and folder `dist/html/*` exists.
On production server execute command `yarn build` (or `yarn build:prod`) where there is no this `html` folder.
